#!/bin/bash
set -x

csv_file=${APP_DIR}/data/inl1_data.csv
stdout=/tmp/stdout
stderr=/tmp/stderr
logfile=/var/log/user-mngt.log
touch "${stdout}"
touch "${stderr}"

# Verify that:
# - the script is installed at /usr/sbin/user-mngt
test "$(which user-mngt)" = "/usr/sbin/user-mngt" || exit 1

# Verify that:
# - the script takes exactly one argument and otherwise prints error to stderr
#   and exit with error code
output=$(sudo user-mngt 2>&1)
test $? -gt 0 || exit 1
test "$(echo "${output}" | head -n 1)" = "Missing required <CSV-FILE> argument" || exit 1

output=$(sudo user-mngt inl1_data.csv abc123 2>&1)
test $? -gt 0 || exit 1
test "$(echo "${output}" | head -n 1)" = "Script 'user-mngt' must be called with exactly one argument" ||
    exit 1

output=$(sudo user-mngt -p inl1_data.csv abc123 2>&1)
test $? -gt 0 || exit 1
test "$(echo "${output}" | head -n 1)" = "Script 'user-mngt' must be called with exactly one argument" ||
    exit 1

# Verify that:
# - the script only accepts a file as an argument
dirpath="/tmp"
output=$(sudo user-mngt ${dirpath} 2>&1)
test $? -gt 0 || exit 1
test "$(echo "${output}" | head -n 1)" = "Specified path '${dirpath}' is not a file" || exit 1

# Verify that:
# 1)  When a user is added with success - "Add <username>" is printed to stdout and logfile
# 1a) When a user add fails - "Error while adding <username>" is printed to stderr
# 2)  When a user is removed with success -  "Remove <username>" is printed to stdout and logfile
# 2a) When a user remove fails - "Error while removing <username>" is printed to stderr
sudo user-mngt "${csv_file}" >"${stdout}" 2>"${stderr}"
test $? -eq 0 || exit 1

while IFS=, read -r fname lname passwd func; do
    username="${fname:0:3}${lname:0:3}"
    if [ "${func}" = "add" ]; then
        if test "$(cat "${stdout}" | grep "Add ${username}")"; then
            test "$(cat "${logfile}" | grep "Add ${username}")" || exit 1
        else
            test "$(cat "${stderr}" | grep "Error while adding user ${username}")" || exit 1
        fi
    elif [ "${func}" = "remove" ]; then
        if test "$(cat "${stdout}" | grep "Remove ${username}")"; then
            test "$(cat "${logfile}" | grep "Remove ${username}")" || exit 1
        else
            test "$(cat "${stderr}" | grep "Error while removing user ${username}")" || exit 1
        fi
    fi
done <"${csv_file}"

# Verify that:
# 1)  When a user is added with success - "Add <username>" is printed to stdout and logfile
# 1a) When a user add fails - "Error while adding <username>" is printed to stderr
# 2)  When a user is removed with success -  "Remove <username>" is printed to stdout and logfile
# 2a) When a user remove fails - "Error while removing <username>" is printed to stderr
sudo user-mngt -p "${csv_file}" >"${stdout}" 2>"${stderr}"
test $? -eq 0 || exit 1

while IFS=, read -r fname lname passwd func; do
    username="${fname:0:3}${lname:0:3}"
    if [ "${func}" = "add" ]; then
        if test "$(cat "${stdout}" | grep "Add ${username}")"; then
            test "$(cat "${logfile}" | grep "Add ${username}")" || exit 1
        else
            test "$(cat "${stderr}" | grep "Error while adding user ${username}")" || exit 1
        fi
    elif [ "${func}" = "remove" ]; then
        if test "$(cat "${stdout}" | grep "Remove ${username}")"; then
            test "$(cat "${logfile}" | grep "Remove ${username}")" || exit 1
        else
            test "$(cat "${stderr}" | grep "Error while removing user ${username}")" || exit 1
        fi
    fi
done <"${csv_file}"
