version: '3.8'
services:
  debian:
    build:
      context: .
    environment:
      - .env
    image: ${IMAGE_NAME}
    container_name: ${SERVICE_NAME}
    volumes:
      - ${PWD}:${WORKDIR}
    working_dir: ${WORKDIR}

