version: '3.8'
services:
  assignment1:
    build:
      context: ../..
      dockerfile: ./docker/assignment1/Dockerfile
    environment:
      - ./docker/assignment1/.env
    image: ${IMAGE_NAME}
    container_name: ${SERVICE_NAME}
    volumes:
      - ../..:${WORKDIR}
    working_dir: ${WORKDIR}
    hostname: ${SERVICE_NAME}
    user: ${USER_ID}:${GROUP_ID}